export const ErrorCodes = {
    AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
    AUTHORIZATION_FAILED: 'AUTHORIZATION_FAILED',
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    VALIDATION_FAILED: 'VALIDATION_FAILED',
    INFRASTRUCTURE_FAILURE: 'INFRASTRUCTURE_FAILURE',
} as const;

export type ErrorCode =
    (typeof ErrorCodes)[keyof typeof ErrorCodes];